name: "Backend tests"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  withplugins:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
      (github.event_name != 'pull_request')
      || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: with Plugins
    runs-on: ubuntu-latest
    steps:
            -
              name: Install libreoffice
              uses: awalsh128/cache-apt-pkgs-action@v1.4.2
              with:
                packages: libreoffice libreoffice-pdfimport
                version: 1.0
            -
              name: Install etherpad core
              uses: actions/checkout@v3
              with:
                repository: ether/etherpad-lite
                path: etherpad-lite
            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                version: 8
                run_install: false
            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-
            -
              name: Checkout plugin repository
              uses: actions/checkout@v3
              with:
                path: plugin
            -
              name: Determine plugin name
              id: plugin_name
              run: |
                cd ./plugin
                echo "::set-output name=plugin_name::$(node -p "require('./package.json').name")"
            -
              name: Rename plugin directory
              run: |
                pnpm link --global
              env:
                PLUGIN_NAME: ${{ steps.plugin_name.outputs.plugin_name }}
            - name: Link plugin to etherpad-lite
              working-directory: ./etherpad-lite
              run: |
                pnpm link --global $PLUGIN_NAME
            - name: Remove tests
              working-directory: ./etherpad-lite
              run: rm -rf ./src/tests
            -
              name: Install Etherpad core dependencies
              working-directory: ./etherpad-lite
              run: bin/installDeps.sh
            - name: List test files
              working-directory: ./etherpad-lite/src
              run: ls ../node_modules/
            -
              name: Run the backend tests
              working-directory: ./etherpad-lite
              run: pnpm run test
